#!/bin/bash
set -e
rm -rf "$DEST"

# This script exists as backwards compatibility for CI
(
	DEST="${DEST}-client"
	ABS_DEST="${ABS_DEST}-client"
	. hack/make/binary-client
)
(
	DEST="${DEST}-daemon"
	ABS_DEST="${ABS_DEST}-daemon"
	. hack/make/binary-daemon
)
(
	DEST="${DEST}-cowman"
	ABS_DEST="${ABS_DEST}-cowman"
	. hack/make/binary-cowman
)
