name: Close Pull Request

on:
  pull_request_target:
    types: [opened]
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@9c18513d320d7b2c7185fb93396d0c664d5d8448
      with:
        comment: "This repository has been migrated to https://github.com/containers/container-libs. Please open your PR there."
